# TCL File Generated by Component Editor 18.1
# Wed Dec 29 09:17:01 CET 2021
# DO NOT MODIFY


# 
# LCD_controller "LCD_controller" v1.0
#  2021.12.29.09:17:01
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME LCD_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LCD_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCD_controller.vhd VHDL PATH ../hdl/LCD_controller.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink nReset reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AS_Address address Input 2
add_interface_port avalon_slave AS_Read read Input 1
add_interface_port avalon_slave AS_ReadData readdata Output 32
add_interface_port avalon_slave AS_Writedata writedata Input 32
add_interface_port avalon_slave AS_write write Input 1
add_interface_port avalon_slave AS_Wait waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master AM_Address address Output 32
add_interface_port avalon_master AM_read read Output 1
add_interface_port avalon_master AM_wait waitrequest Input 1
add_interface_port avalon_master read_data readdata Input 32
add_interface_port avalon_master readdatavalid readdatavalid Input 1
add_interface_port avalon_master burstcount burstcount Output 5


# 
# connection point data
# 
add_interface data conduit end
set_interface_property data associatedClock clock
set_interface_property data associatedReset ""
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data data readdata Output 16


# 
# connection point DCX
# 
add_interface DCX conduit end
set_interface_property DCX associatedClock clock
set_interface_property DCX associatedReset ""
set_interface_property DCX ENABLED true
set_interface_property DCX EXPORT_OF ""
set_interface_property DCX PORT_NAME_MAP ""
set_interface_property DCX CMSIS_SVD_VARIABLES ""
set_interface_property DCX SVD_ADDRESS_GROUP ""

add_interface_port DCX DCX writeresponsevalid_n Output 1


# 
# connection point CSX
# 
add_interface CSX conduit end
set_interface_property CSX associatedClock clock
set_interface_property CSX associatedReset ""
set_interface_property CSX ENABLED true
set_interface_property CSX EXPORT_OF ""
set_interface_property CSX PORT_NAME_MAP ""
set_interface_property CSX CMSIS_SVD_VARIABLES ""
set_interface_property CSX SVD_ADDRESS_GROUP ""

add_interface_port CSX CSX writeresponsevalid_n Output 1


# 
# connection point LCD_ON
# 
add_interface LCD_ON conduit end
set_interface_property LCD_ON associatedClock clock
set_interface_property LCD_ON associatedReset ""
set_interface_property LCD_ON ENABLED true
set_interface_property LCD_ON EXPORT_OF ""
set_interface_property LCD_ON PORT_NAME_MAP ""
set_interface_property LCD_ON CMSIS_SVD_VARIABLES ""
set_interface_property LCD_ON SVD_ADDRESS_GROUP ""

add_interface_port LCD_ON LCD_ON writeresponsevalid_n Output 1


# 
# connection point RDX
# 
add_interface RDX conduit end
set_interface_property RDX associatedClock clock
set_interface_property RDX associatedReset ""
set_interface_property RDX ENABLED true
set_interface_property RDX EXPORT_OF ""
set_interface_property RDX PORT_NAME_MAP ""
set_interface_property RDX CMSIS_SVD_VARIABLES ""
set_interface_property RDX SVD_ADDRESS_GROUP ""

add_interface_port RDX RDX writeresponsevalid_n Output 1


# 
# connection point RESX
# 
add_interface RESX conduit end
set_interface_property RESX associatedClock clock
set_interface_property RESX associatedReset ""
set_interface_property RESX ENABLED true
set_interface_property RESX EXPORT_OF ""
set_interface_property RESX PORT_NAME_MAP ""
set_interface_property RESX CMSIS_SVD_VARIABLES ""
set_interface_property RESX SVD_ADDRESS_GROUP ""

add_interface_port RESX RESX writeresponsevalid_n Output 1


# 
# connection point WRX
# 
add_interface WRX conduit end
set_interface_property WRX associatedClock clock
set_interface_property WRX associatedReset ""
set_interface_property WRX ENABLED true
set_interface_property WRX EXPORT_OF ""
set_interface_property WRX PORT_NAME_MAP ""
set_interface_property WRX CMSIS_SVD_VARIABLES ""
set_interface_property WRX SVD_ADDRESS_GROUP ""

add_interface_port WRX WRX writeresponsevalid_n Output 1

